<?php

/**
 * @file
 * Functions to support theming in the solidify theme.
 */

function solidify_theme_suggestions_breadcrumb_alter(array &$suggestions, array $variables) {
  $suggestions[] = "breadcrumb__solidify";
}

function solidify_theme_suggestions_pager_alter(array &$suggestions, array $variables) {
  $suggestions[] = "pager__news";
}

function solidify_theme_suggestions_bef_links_alter(array &$suggestions, array $variables) {
  $suggestions[] = "bef_links__exposed_tags";
}
